### ISSUE TITLE
explore avenues or the possibility to automate flagging of checklists that get included in results summarization

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#203] opened 2019-02-23 20:06 UTC
Aha! Link: https://nditech.aha.io/features/APOLLO-160

**Comment by SarahCooperNDI** [comment] 2019-05-16 15:24
@blynchNDI @takinbo From my perspective this issue can be closed

**Comment by blynchNDI** [comment] 2019-05-16 15:51
Closing per Sarah C's comment

**Comment by SarahCooperNDI** [comment] 2019-06-04 17:36
Reopening -- I know we discussed this in Nigeria and said it could be done through QA per Tim's proposal -- however, thinking about this and after discussing with Richard that won't actually work. I believe that right now Apollo only includes observer reports in the results analysis if the sum of all votes cast is non-null and non-zero, if the total registered voters is non-null and non-zero and if rejected ballots is non-null.  We would like the possibility to specify these paramaters as pat of the Form Properties.  Right now we can specify a field for accredited voters, blank votes, invalid votes and registered voters in the form builder.  We would like to be able to specify more fields (like which fields include the vote shares for the parties/candidates) and to define the parameters for each field under which it should be included in the results analysis.  Tim is correct that we can absolutely set the parameters in QA -- but unless we have some way of telling Apollo that we only want records that do not fail a certain QA check to be pulled into the automated results analysis that doesn't really help us.  Does this make sense?  Happy to discuss in more detail if needed.

**Comment by SarahCooperNDI** [comment] 2019-06-11 21:47
We are all agreed that there are very few edge cases where we would need to set very particular parameters for results summary. What we would need to be able to do on a consistent basis is the following:

1) Identify where on the checklist the following fields are contained:
- Registered voters
- Accredited voters (primarily applies to Nigeria but looks like this field already exists in the 3.0 form builder
- Vote shares for each candidate/party
**This could potentially be done by either identifying every field with a party or candidate or by identifying a range? e.g. FA, FB, FC, FG and FH or FA-FH
- Blank ballots
- Rejected ballots

2) Ensure that checklists are only pulled into the results summary when the values of ALL of these fields are non-null (when they are defined).  In addition, we would only want checklists to be pulled into results summary when the registered voters field is not equal to 0 and when the sum of votes for every candidate/party is not equal to 0.

**Comment by blynchNDI** [comment] 2019-08-10 15:29
The implementation looks very good and intuitive. For @SarahCooperNDI per your comment, you said that checklists should only be pulled into the results summary when the registered voters field is non-zero. Currently, if the registered voter field is not defined/identified, then no checklists are pulled in. Assuming there are cases of elections in which registered voters will not be used, then there should be a fix made so that the requirement of registered voters not being zero should be dropped when that field is not defined

**Comment by blynchNDI** [comment] 2019-08-15 16:00
Per comments from Richard, it sounds like Registered Voters should be treated as a required/necessary field, and therefore this is working as intended. It might be good to specify that 'votes share' and 'registered voters' are necessary fields for the results analysis to appear - perhaps #182 would be the best place to address this.

**Closed by blynchNDI** 2019-08-15 16:00 UTC
Labels: Apollo 3, help wanted
