### ISSUE TITLE
add in an additional filter to see ALL DATA, QUARANTINED DATA, NOT QUARANTINED DATA. The default filter should be NOT QUARANTINED

### ISSUE THREAD

**Issue by takinbo** [nditech/apollo#222] opened 2019-02-23 21:28 UTC
Aha! Link: https://nditech.aha.io/features/APOLLO-141

**Comment by blynchNDI** [comment] 2019-04-30 17:39
As mentioned to Tim on the call, there are two things remaining here: 
1. Rename the labels on the dropdown menu to match the labels in the title of this issue
2. @SarahCooperNDI can confirm, but I think rather than having the menu default to the header 'Quarantine Status' which is the same as 'All Data', there should just be the three options, and the menu should default to 'Not Quarantined Data', with 'All Data' and 'Quarantined Data' as the two other options on the menu.

**Comment by takinbo** [comment] 2019-05-01 10:44
The reason we implemented it the way we did: Quarantine Status (representing no selection and so showing all data), Quarantine None, Quarantine All, Quarantine Results was due to the fact that those widgets don't have a label so seeing (All Data) as a selection can be confusing as to what it means. We prefix all the options in the drop downs with a meaningful label to give the user an idea of what that selection was for.

Thoughts?

**Comment by SarahCooperNDI** [comment] 2019-05-01 13:44
@takinbo @blynchNDI We want the default applied filter to be Not Quarantined versus All Data because clerks might forget to filter on Not Quarantined and could end up chasing data for records that we no longer care about.  I will take a look at the drop-down menu labels and provide additional feedback after our call

**Comment by blynchNDI** [comment] 2019-05-01 21:01
Moving this back into progress for addressing the feedback in Sarah Cooper's comment above ^

**Comment by SarahCooperNDI** [comment] 2019-05-13 22:21
Suggestion from @RLK-NDI on quarantine menu structure - could the options be expanded to include:

1) Not Quarantined (default) - (Quarantine Status = None)
2) Quarantine All - (Quarantine Status = All)
3) Quarantine Results - (Quarantine Status = Results)
4) Quarantine All & Results - (Quarantine Status = All or = Results).
5) All Checklists (Quarantine Status = None or = All or = Results)

@takinbo @dodumosu

**Comment by blynchNDI** [comment] 2019-05-14 14:50
^ Just to note the current status of things, currently options 1, 2, and 3 exist, with 1 is the default filter. So the only additional work will be renaming "Quarantine None" to "Not Quarantined" for option 1, and adding options 4 and 5.

**Comment by blynchNDI** [comment] 2019-07-30 16:59
Looks good - only thing to discuss tomorrow is whether one or two of the labels should be changed

**Comment by blynchNDI** [comment] 2019-07-31 19:12
Per Richard's preference, the only additional request here is for:
-The default filter to be all checklists displayed regardless of whether they are quarantined
-This filter should be called 'Quarantine Status' in line with the naming conventions for the other filters

**Comment by takinbo** [comment] 2019-08-01 13:40
Resolved in #451

**Closed** 2019-08-01 14:40 UTC
Labels: Apollo 3, enhancement
