### ISSUE TITLE
BUG FIX: Manually entering checklist data in test event generates 502 error

### ISSUE THREAD

**Issue by SarahCooperNDI** [nditech/apollo#357] opened 2019-05-31 15:28 UTC
Michael attempted to enter checklist data for participant 11111 in the Testing event.  Although the data saved, he said it took a very long time and generated a 502 error (pasted below).

Error 502 
Ray ID: 4df944f5d850c1d9 • 2019-05-31 13:25:11 UTC
Bad gateway

He later tried to replicate the error with participant 11025 and the data saved correctly without any problems.

**Comment by takinbo** [comment] 2019-05-31 17:59
This may be happening due to on-going updates of the application through the container. Closing this for now. Please re-open if you can reproduce this repeatedly and get a 503 Zomg error instead of a 502 which is application server related.

**Closed by takinbo** 2019-05-31 17:59 UTC
Labels: Apollo 3, bug
