### ISSUE TITLE
create profiles for data clerks…

### ISSUE THREAD

**Issue by dodumosu** [nditech/apollo#227] opened 2019-02-23 21:57 UTC
…so that it is possible to view information about how many times they have attempted to contact observers, and a log of any records they have modified

see #169 and #198

Aha! Link: https://nditech.aha.io/features/APOLLO-136

**Comment by takinbo** [comment] 2019-06-15 08:41
duplicate of #198

**Closed by takinbo** 2019-06-15 08:41 UTC
Labels: Apollo 3, enhancement, help wanted
